# ruff: noqa: F405
"""Single-user identity and access helpers — canonical implementation lives in ``lumen``."""

from __future__ import annotations

from lumen.shared._util.user import *  # noqa: F401,F403

__all__ = [
    "AUTH_DIR",
    "ADMIN_WORKSPACE_ROOT",
    "ADMIN_PREFIX",
    "AVATAR_EXTENSIONS",
    "CurrentUser",
    "KnowledgeResource",
    "LOCAL_ADMIN_ID",
    "LOCAL_ADMIN_USERNAME",
    "PROJECT_ROOT",
    "Role",
    "SECRET_FILE",
    "SYSTEM_ROOT",
    "ScopeKind",
    "USERS_FILE",
    "UserRecord",
    "UserScope",
    "USER_PREFIX",
    "admin_catalog",
    "admin_catalog_service",
    "admin_kb_base_dir",
    "admin_kb_manager",
    "admin_scope",
    "allowed_llm_options",
    "allowed_mcp_tools",
    "allowed_optional_tools",
    "apply_allowed_llm_selection",
    "assert_skill_allowed",
    "assert_writable",
    "assigned_skill_detail",
    "assigned_skill_ids",
    "assigned_skill_infos",
    "current_kb_base_dir",
    "current_kb_manager",
    "current_owner_id",
    "delete_avatar_file",
    "delete_user",
    "exec_override",
    "get_admin_path_service",
    "get_avatar_file",
    "get_current_path_service",
    "get_current_user",
    "get_current_user_or_none",
    "get_owner_path_service",
    "get_owner_secrets_dir",
    "get_path_service_for_scope",
    "get_user",
    "get_user_by_id",
    "has_capability_access",
    "list_user_info",
    "list_visible_knowledge_bases",
    "load_or_create_auth_secret",
    "load_users",
    "local_admin_user",
    "manager_for_resource",
    "merge_personal_llm_profiles",
    "new_user_id",
    "owner_catalog_service",
    "owner_secrets_dir",
    "personal_llm_rows",
    "redacted_model_access",
    "reset_current_user",
    "resolve_for_rag",
    "resolve_kb",
    "resolve_kb_manifest",
    "resolve_kb_metadata",
    "save_avatar_file",
    "save_user",
    "set_avatar",
    "set_current_user",
    "set_role",
    "user_context",
    "user_from_token_payload",
]
