import { test, expect, Page } from '@playwright/test'
import { mockDialogApi } from './dialog-api'

async function openHome(page: Page) {
  await mockDialogApi(page)
  await page.addInitScript(() => {
    localStorage.setItem('trae:sidebarOpen', '1')
    localStorage.setItem('trae:statusOpen', '0')
    localStorage.setItem('trae:theme', 'dark')
    sessionStorage.setItem('trae:view', 'chat')
  })
  await page.goto('/')
  await page.waitForSelector('.app-root')
}

test.describe('sidebar hover and composer menus', () => {
  test('悬停对话短标题出现完整标题浮层', async ({ page }) => {
    await openHome(page)
    const title = page.locator('.taskItem .taskText').first()
    await expect(title).toBeVisible()
    await title.hover()
    const tip = page.locator('[role="tooltip"] .tooltipTitle')
    await expect(tip).toBeVisible({ timeout: 1500 })
    await expect(tip).toHaveText((await title.innerText()).trim())
    await expect(page.locator('[role="tooltip"] .tooltipMetaText').filter({ hasText: '云端任务' })).toBeVisible()
    await expect(page.locator('[role="tooltip"] .tooltipMetaText').filter({ hasText: '更新于' })).toBeVisible()
    const tipBox = await page.locator('[role="tooltip"]').boundingBox()
    const sidebar = await page.locator('.sidebar-IlIa2h').boundingBox()
    expect(tipBox).toBeTruthy()
    expect(sidebar).toBeTruthy()
    expect(tipBox!.x).toBeGreaterThanOrEqual(sidebar!.x + sidebar!.width - 1)
  })

  test('悬停行露出置顶和更多，点击更多弹出菜单', async ({ page }) => {
    await openHome(page)
    const row = page.locator('.taskItem').first()
    await row.hover()
    await expect(row.locator('.taskMoreBtn')).toBeVisible()
    await expect(row.locator('[aria-label="置顶"]')).toBeVisible()
    await expect(row.locator('.trae-icon-pin-line')).toBeVisible()
    await row.locator('.taskMoreBtn').click()
    const menu = page.locator('.taskMenu')
    await expect(menu).toBeVisible()
    await expect(menu.getByRole('menuitem', { name: '置顶任务' })).toBeVisible()
    await expect(menu.getByRole('menuitem', { name: '重命名' })).toBeVisible()
    await expect(menu.getByRole('menuitem', { name: '删除任务' })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(menu).toHaveCount(0)
  })

  test('点击 + 弹出菜单，不立刻打开文件选择', async ({ page }) => {
    await openHome(page)
    await page.locator('.navItem-r4wswG').filter({ hasText: '新建对话' }).click()
    const plus = page.locator('.messageInputChatInputHome .messageInputToolbarIconBtn')
    await expect(plus).toHaveAttribute('aria-expanded', 'false')
    await plus.click()
    await expect(plus).toHaveAttribute('aria-expanded', 'true')
    const menu = page.locator('.cascadeMenuContent-tUO2DP[role="menu"]')
    await expect(menu).toBeVisible()
    await expect(page.locator('.cascadeMenu-vEfgk4')).toHaveCSS('position', 'fixed')
    await expect(menu.getByRole('menuitem', { name: '上传图片' })).toBeVisible()
    await expect(menu.getByRole('menuitem', { name: '当前项目的文件' })).toBeVisible()
    await expect(menu.getByRole('menuitem', { name: '命令' })).toBeVisible()
    await expect(menu.getByRole('menuitem', { name: '插件' })).toBeVisible()
    await expect(menu.getByRole('menuitem', { name: '技能' })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(plus).toHaveAttribute('aria-expanded', 'false')
    await expect(menu).toHaveCount(0)
  })

  test('插件 / 能力 / 麦克风 / 发送 的打开与悬停外形', async ({ page }) => {
    await openHome(page)
    await page.locator('.navItem-r4wswG').filter({ hasText: '新建对话' }).click()

    const plugin = page.locator('.messageInputChatInputHome .messageInputPluginToolbar')
    await plugin.hover()
    await expect(page.locator('[role="tooltip"] .tooltipPlainText').filter({ hasText: '调用插件' })).toBeVisible({ timeout: 1500 })
    await plugin.click()
    await expect(plugin).toHaveClass(/messageInputPluginToolbarActive/)
    await expect(page.locator('.availablePluginsPopover-lLsv2r')).toBeVisible()
    await expect(page.locator('.availablePluginsHeader-P_cU8B')).toHaveText('可用插件')
    await expect(page.getByRole('button', { name: '管理插件' })).toBeVisible()
    await expect(page.getByRole('button', { name: '探索更多插件' })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.locator('.availablePluginsPopover-lLsv2r')).toHaveCount(0)

    const model = page.locator('.messageInputChatInputHome .core-model-select-trigger')
    await model.hover()
    await model.click()
    await expect(model).toHaveAttribute('aria-expanded', 'true')
    await expect(model).toHaveAttribute('data-state', 'open')
    const list = page.locator('.core-model-select-portal-content[role="listbox"]')
    await expect(list).toBeVisible()
    await expect(list).toHaveAttribute('data-align', 'end')
    const listBox = await list.boundingBox()
    const triggerBox = await model.boundingBox()
    expect(listBox).toBeTruthy()
    expect(triggerBox).toBeTruthy()
    expect(listBox!.height).toBeGreaterThan(80)
    expect(Math.abs((listBox!.x + listBox!.width) - (triggerBox!.x + triggerBox!.width))).toBeLessThan(4)
    expect(triggerBox!.y - (listBox!.y + listBox!.height)).toBeGreaterThanOrEqual(2)
    await expect(list.getByRole('option', { name: '对话' })).toBeVisible()
    await list.getByRole('option', { name: '引导学习' }).click()
    await expect(model).toHaveAttribute('aria-expanded', 'false')
    await expect(model).toContainText('引导学习')

    const mic = page.locator('.messageInputChatInputHome .rtcVoicePluginButton')
    await mic.hover()
    await expect(page.locator('[role="tooltip"] .tooltipPlainText').filter({ hasText: '语音输入' })).toBeVisible({ timeout: 1500 })

    const send = page.locator('.messageInputChatInputHome .chat-input-v2-send-button')
    await expect(send).toHaveClass(/voice-call-mode/)
    await send.hover()
    await expect(page.locator('[role="tooltip"] .tooltipPlainText').filter({ hasText: '语音讨论' })).toBeVisible({ timeout: 1500 })
  })
})
