#!/usr/bin/env python
"""Prepare ``lumen_web`` package data from a Vite production build."""

from __future__ import annotations

import argparse
from pathlib import Path
import shutil
import subprocess

PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEB_DIR = PROJECT_ROOT / "frontend"
PACKAGE_DIR = PROJECT_ROOT / "lumen_web"


def _clean_package_dir(package_dir: Path) -> None:
    package_dir.mkdir(parents=True, exist_ok=True)
    init_file = package_dir / "__init__.py"
    init_text = init_file.read_text(encoding="utf-8") if init_file.exists() else ""
    for child in package_dir.iterdir():
        if child.name == "__init__.py":
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()
    if init_text:
        init_file.write_text(init_text, encoding="utf-8")


def prepare_web_package(*, skip_build: bool = False) -> None:
    if not skip_build:
        subprocess.run(["npm", "run", "build"], cwd=WEB_DIR, check=True)

    dist = WEB_DIR / "dist"
    if not (dist / "index.html").exists():
        raise SystemExit(
            "Missing frontend/dist/index.html. Run this script after `npm run build` "
            "or omit --skip-build."
        )

    _clean_package_dir(PACKAGE_DIR)
    shutil.copytree(dist, PACKAGE_DIR, dirs_exist_ok=True)
    (PACKAGE_DIR / "BUILD_INFO").write_text(
        "Generated by scripts/prepare_web_package.py from frontend/dist.\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Copy an existing frontend/dist build without running npm.",
    )
    args = parser.parse_args()
    prepare_web_package(skip_build=args.skip_build)


if __name__ == "__main__":
    main()
